# Generated by Django 5.2.6 on 2025-10-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='person',
            new_name='Person',
        ),
    ]
