# Generated by Django 5.2.6 on 2025-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Social', '0002_rename_person_profile_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('propic', models.ImageField(blank=True, default='def_user.png', upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Person',
            new_name='person',
        ),
    ]
