# Generated by Django 5.2.6 on 2025-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Social', '0005_user_remove_profile_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='propic',
            field=models.ImageField(blank=True, default='def_user.png', upload_to=''),
        ),
    ]
