# Generated by Django 5.2.6 on 2025-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Social', '0006_user_propic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='propic',
            field=models.ImageField(blank=True, default='def_user.png', upload_to=''),
        ),
    ]
