# Generated by Django 5.2.6 on 2025-10-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Social', '0007_delete_user_profile_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='def_user.png', upload_to=''),
        ),
    ]
